apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-jmeter
  namespace: argocd
  finalizers:
    - resources-finalize.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/crunchy-devops/argocd-15-min.git
    targetRevision: HEAD
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true